### ISSUE TITLE
Inappropriate error message when no GDB installed

### ISSUE THREAD

**Issue by febeling** [david942j/gdb-ruby#32]
Trying to install and run as documented results in this error:

```
$ rbenv shell 2.5.3                                                                                                       
febeling:~/ $ gem install gdb                                                                                                                   [13:32:30]
Fetching: dentaku-3.3.0.gem (100%)
Successfully installed dentaku-3.3.0
Fetching: memory_io-0.1.1.gem (100%)
Successfully installed memory_io-0.1.1
Fetching: gdb-0.3.0.gem (100%)
Successfully installed gdb-0.3.0
3 gems installed
febeling:~/ $ gdb-ruby -q bash                                                                                                                  [13:32:39]
Traceback (most recent call last):
	6: from /Users/febeling/.rbenv/versions/2.5.3/bin/gdb-ruby:23:in `<main>'
	5: from /Users/febeling/.rbenv/versions/2.5.3/bin/gdb-ruby:23:in `load'
	4: from /Users/febeling/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/gdb-0.3.0/bin/gdb-ruby:9:in `<top (required)>'
	3: from /Users/febeling/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/gdb-0.3.0/bin/gdb-ruby:9:in `new'
	2: from /Users/febeling/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/gdb-0.3.0/lib/gdb/gdb.rb:29:in `initialize'
	1: from /Users/febeling/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/gdb-0.3.0/lib/gdb/gdb.rb:284:in `spawn'
/Users/febeling/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/gdb-0.3.0/lib/gdb/gdb.rb:284:in `spawn': No such file or directory - fork failed (Errno::ENOENT)
```

**Comment by david942j** [comment]
Looks like your OS is macOS? This project is for Linux only (unless you have your mac install gdb, the gnu debugger)

**Comment by febeling** [comment]
I used gdb many times on macOS, but you're right that it was not installed this time around. Thanks for the pointer. 

After installation of gdb it fails with a different message:
```
/Users/febeling/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/gdb-0.3.0/lib/gdb/gdb.rb:285:in `ioctl': Inappropriate ioctl for device @ rb_ioctl - /dev/ttys009 (Errno::ENOTTY)
```
But if you don't target non-linux systems, maybe the issue should just be closed.

**Comment by david942j** [comment]
I didn't intend to support macOS, but I'm willing to take this issue as a macOS-support request and give it a try.

**Comment by david942j** [comment]
I fixed the original issue with showing proper error message if GDB is not installed in the system.
I will open another issue/pr for macOS supporting

**Comment by febeling** [comment]
Very cool. I've subscribed to that.
