### ISSUE TITLE
`winsize=': no implicit conversion of false into Integer (TypeError)

### ISSUE THREAD

**Issue by rschwass** [david942j/gdb-ruby#40]
I hate to be the bearer of bad news.

Here is my script

```
#!/usr/bin/ruby

require 'gdb'
gdb = GDB::GDB.new('bash')
```

and here is the exception it throws:
```
ruby sploit.rb
/var/lib/gems/2.3.0/gems/gdb-1.0.0/lib/gdb/gdb.rb:332:in `winsize=': no implicit conversion of false into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/gdb-1.0.0/lib/gdb/gdb.rb:332:in `spawn'
	from /var/lib/gems/2.3.0/gems/gdb-1.0.0/lib/gdb/gdb.rb:37:in `initialize'
	from sploit.rb:4:in `new'
	from sploit.rb:4:in `<main>'

```

Its throwing on 
```
gdb = GDB::GDB.new('bash')
```

Thanks in advance.

**Comment by rschwass** [comment]
fix:
```
gem update io-console
```
from io-console (0.4.5) to 0.4.7
